server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/AgriculturalSystem?serverTimezone=Asia/Shanghai
    username: root
    password: 111111

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mybatis/mapper/*.xml

weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxdcd57ff726ed6a89
  secret: 3d6725335369c7317568fa510c278ea2

bigTypeImagesFilePath: G://graduation project/bigTypeImgs/

productImagesFilePath: G://graduation project/productImgs/

swiperImagesFilePath: G://graduation project/swiperImgs/

productSwiperImagesFilePath: G://graduation project/productSwiperImgs/